# Dreamhost custom configuration for Nginx
#
# Updated Fall 2026
# Changed from apache setup to Nginx setup. The old .htaccess file is no longer used.
# Apache was extremely slow.
# 
# Note that this does NOT require that Dreamhost's panel be setup for proxy /api.
# See the location block.

# 1. Protect static assets (returns a strict 404 if a file is missing)
location /static/ {
    try_files $uri =404;
}

# 2. Anything on the /api path should be proxied to the node server.  This is configured in the Dreamhost panel,
# but because dreamhost we use location, we need to reset it here as well.
#  Note: we need /api/ with the trailing slash, because the proxy is configured to forward /api/* to the backend.  
# The destination MUST NOT HAVE the slash, and needs http
location /api/ {
   proxy_http_version 1.1;
   proxy_pass http://127.0.0.1:9000;
   proxy_set_header Host $host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

   # Give the backend buffer room to respond during a heavy reload
   # Fixes problem where very fast reloads of the page would cause a 502 error because the backend was not ready to respond.
   proxy_next_upstream error timeout invalid_header http_502;
   proxy_next_upstream_tries 3;
   
   # Give the backend a 5-second buffer window to recover
   proxy_connect_timeout 5s;
   proxy_read_timeout 60s;
}


# 3. Fallback for React Router navigation for all but /api path.
location / {
    try_files $uri $uri/ /index.html;
}
